# Generated by Django 5.0.1 on 2024-02-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variety',
            unique_together=set(),
        ),
    ]
