# Generated by Django 4.2.7 on 2023-11-15 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='top_product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
