# Generated by Django 4.2.7 on 2023-12-04 17:34

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='code',
            field=colorfield.fields.ColorField(default='FF0000', image_field=None, max_length=25, samples=None, unique=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
