# Generated by Django 5.0.1 on 2024-02-15 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_cartitem_variety'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='unit_peice',
            new_name='unit_price',
        ),
    ]
