# Generated by Django 5.0.1 on 2024-02-18 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_unit_peice_orderitem_unit_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'object_id')},
        ),
    ]
