# Generated by Django 4.2.7 on 2023-12-04 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_mobileimage_alter_mobile_image_delete_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobile',
            name='image',
        ),
        migrations.AddField(
            model_name='mobileimage',
            name='mobile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='mobile_images', to='store.mobile'),
            preserve_default=False,
        ),
    ]
