# Generated by Django 5.0.1 on 2024-05-16 14:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_dpro'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadPhone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('detatime_modified', models.DateTimeField(auto_now=True)),
                ('available', models.BooleanField(default=True)),
                ('form_factor', models.CharField(max_length=255)),
                ('power_supply', models.CharField(max_length=255)),
                ('connectivity_tec', models.CharField(max_length=255)),
                ('another_features', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='store.category')),
                ('discount', models.ManyToManyField(blank=True, to='store.discount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Dpro',
        ),
    ]
