# Generated by Django 4.2.7 on 2023-12-04 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_mobile_image_mobileimage_mobile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mobilevariety',
            unique_together={('color', 'mobile')},
        ),
    ]
