# Generated by Django 4.2.7 on 2023-12-04 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_mobilevariety_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilevariety',
            name='inventory',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
