# Generated by Django 4.2.7 on 2023-12-04 18:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_mobilevariety_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobilevariety',
            name='inventory',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
