# Generated by Django 5.0.1 on 2024-02-25 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variety',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_vars', to='store.variety'),
        ),
    ]
