# Generated by Django 4.2.7 on 2023-12-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_mobilevariety_inventory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_sub',
            new_name='is_parent',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='sub_category',
            new_name='parent',
        ),
    ]
