# Generated by Django 4.2.7 on 2023-12-08 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_rename_is_sub_category_is_parent_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_parent',
            new_name='is_sub',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='parent',
            new_name='sub_category',
        ),
    ]
