# Generated by Django 5.0.1 on 2024-05-29 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_profile_birth_date_remove_profile_ssn'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='ssn',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
